import React, {Component} from 'react';
import arrowIcon from '../../img/baseline_arrow_forward_black_48dp.png';

const dictados = [
    {
        key: "1",
        title: "dictado 1",
        content: "Este es el dictado numero 1",
        difficulty: "easy",
        language: "ES",
        rightIcon: arrowIcon,
    },
    {
        key: "2",
        title: "dictado 2",
        content: "Este es el dictado numero 2",
        difficulty: "medium",
        language: "ES",
        rightIcon: arrowIcon,
    },
    {
        key: "3",
        title: "dictado 3",
        content: "Este es el dictado numero 3",
        difficulty: "medium",
        language: "EN",
        rightIcon: arrowIcon,
    },
    {
        key: "4",
        title: "dictado 4",
        content: "Este es el dictado numero 4",
        difficulty: "easy",
        language: "FR",
        rightIcon: arrowIcon,
    },
    {
        key: "5",
        title: "dictado 5",
        content: "Este es el dictado numero 5",
        difficulty: "hard",
        language: "DE",
        rightIcon: arrowIcon,
    },
    {
        key: "6",
        title: "dictado 6",
        content: "Este es el dictado numero 6",
        difficulty: "medium",
        language: "FR",
        rightIcon: arrowIcon,
    },
    {
        key: "7",
        title: "dictado 7",
        content: "Este es el dictado numero 7",
        difficulty: "easy",
        language: "ES",
        rightIcon: arrowIcon,
    },
    {
        key: "8",
        title: "dictado 8",
        content: "Este es el dictado numero 8",
        difficulty: "hard",
        language: "EN",
        rightIcon: arrowIcon,
    },
    {
        key: "9",
        title: "dictado 9",
        content: "Este es el dictado numero 9",
        difficulty: "hard",
        language: "IT",
        rightIcon: arrowIcon,
    },
    {
        key: "10",
        title: "dictado 10",
        content: "Este es el dictado numero 10",
        difficulty: "medium",
        language: "ES",
        rightIcon: arrowIcon,
    },
    {
        key: "11",
        title: "dictado 11",
        content: "Este es el dictado numero 11",
        difficulty: "easy",
        language: "IT",
        rightIcon: arrowIcon,
    },
    {
        key: "12",
        title: "dictado 12",
        content: "Este es el dictado numero 12",
        difficulty: "medium",
        language: "FR",
        rightIcon: arrowIcon,
    },
]

export default dictados;